batchSize: 128
epochs: 5
githubRepository: https://github.com/jamesHargreaves12/SimpleML.git
modelType: Simple
pathToModuleCode: C:\Users\james.hargreaves\PycharmProjects\SimpleMLRepo
totalTrainingSize: 1000
